# Generated by Django 2.2.5 on 2019-10-05 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mysite',
            name='author',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='mysite',
            name='num',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='mysite',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
